import type { RequiredDataFromCollectionSlug } from 'payload'

const toItems = (names: string[]) => names.map((name) => ({ name }))

const events = [
  'Elkhart Co. 4-H Fair',
  'Goshen Community Schools',
  'American Cancer Society',
  'Spring Riot (Western Michigan U.)',
  'Pro-Life Music Festival',
  'NorthWood High School',
  'LaGrange Co. Fair',
  'Bristol Homecoming',
  'LaGrange REMC',
  'Goshen College',
  'Trinity United Methodist Church',
  'Wawasee High School',
  'Calvary UMC',
  'Downtown @ 8:08',
  'Student Ventures (NC)',
  'Cow Jam / Cowboy Up (Mendon, MI)',
  'Fourth Tribe Productions',
  'Between the Buns',
  'Upward Basketball Warsaw / Elkhart',
  'MDA I Muscular Dystrophy Association',
  'Harvest Community Church (Goshen)',
  'Harmony Festival (Three Rivers, MI)',
  'Grace Community (Goshen)',
  'Rhapsody in Green (city of Elkhart)',
  'Oakwood Inn (Syracuse)',
  'River of Life (Elkhart)',
  'Operation Foundation (Ligonier)',
  'Grace UMC (Kokomo, IN)',
  'Traveling Mission Groups',
  'LeSea Broadcasting',
  'Evangelical Methodist Church (General / Yearly Conference - Indianapolis)',
]

const artists = [
  'Jeremy Camp',
  'Skillet',
  'Starfield',
  'Leeland',
  'Rebecca St. James',
  "Brandon Cash (Johnny's son)",
  'Desperation Band',
  'Mark Schultz',
  'Hawk Nelson',
  'Fireflight',
  'Mute Math',
  'Kathy Troccoli',
  'Superchic[k]',
  'Kutless',
  'Brandon Heath',
  'Avalon',
  'Andrew Peterson',
  'Forever (Beatles Tribute)',
  'FEE',
  'Pillar',
  'Sanctus Real',
  'Chris Rice',
  'Barlow Girl',
  'Todd Agnew',
  'Decyfer Down',
  'Over the Rhine',
  'Family Force 5',
  'Tree 63',
  'KJ-52',
  'Everyday Sunday',
  'Glenn Kaiser',
  'Rita Springer',
  'Carrie Newcomer',
  'Bill Mallonee (V.O.L.)',
  'Kenya Safari Acrobats',
  'Bebo Norman',
  'Seventh Day Slumber',
  'Jonah 33',
  'Dick Stoner (Magic Show)',
  'Disciple',
  'Spoken',
  'D.J. Sticky Boots',
  'Selah',
  '4-Him',
  'Stellar Kart',
  'The Elms',
  'Ruth Cook & Belle',
  'David Phelps',
  'Project 86',
  "Taylor Ware (America's Got Talent)",
]

export const clientsStatic: RequiredDataFromCollectionSlug<'pages'> = {
  slug: 'clients',
  _status: 'published',
  hero: {
    type: 'none',
  },
  meta: {
    description:
      'A selection of the events, installations, organizations, and artists Music Express has served.',
    title: 'Clients - Music Express',
  },
  title: 'Clients',
  layout: [
    {
      blockName: 'Page Header',
      blockType: 'pageHeader',
      title: 'Clients',
    },
    {
      blockName: 'Events',
      blockType: 'clientsGrid',
      heading: 'EVENTS, INSTALLATIONS & MORE',
      variant: 'title',
      items: toItems(events),
    },
    {
      blockName: 'Artists',
      blockType: 'clientsGrid',
      heading: 'artists',
      variant: 'heading',
      items: toItems(artists),
      moreText: '......plus, many more!',
    },
  ],
}
